trigger:
  branches:
    include:
      - main/*


pool:
  name: Default

stages:
  - stage: built
    displayName: built
    jobs:
      - job: job_built
        displayName: built
        pool:
          name: Default
        steps:
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
              backendServiceArm: 'hcl_service_connection'
              backendAzureRmStorageAccountName: 'hclstorage01'
              backendAzureRmContainerName: 'hclcontainer'
              backendAzureRmKey: '.tfstate'

          - task: TerraformTask@5
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'

          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'hcl_service_connection'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'

  - stage: scanning
    displayName: scanning
    dependsOn: built
    jobs:
      - job: job_scanning
        displayName: scanning
        pool:
          name: Default
        continueOnError: false
        steps:
          - task: MicrosoftSecurityDevOps@1
            inputs:
              command: 'pre-job'
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              dir: '$(System.DefaultWorkingDirectory)/environment/dev'

  - stage: manualvalidation
    displayName: manual validation
    dependsOn: scanning
    jobs:
      - job:
        displayName: manual validation
        pool:
          name: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'nsn.kapil@gmail.com'
            approvers: 'nsn.kapil@gmail.com'

  - stage: deploy
    displayName: deploy
    dependsOn: manualvalidation
    jobs:
      - job: 
        displayName: deploy
        pool: Default
        steps:
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
              backendServiceArm: 'hcl_service_connection'
              backendAzureRmStorageAccountName: 'hclstorage01'
              backendAzureRmContainerName: 'hclcontainer'
              backendAzureRmKey: '.tfstate'              

          - task: TerraformTask@5
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
              commandOptions: 'apply -auto-approve'
              outputTo: 'console'
              environmentServiceNameAzureRM: 'hcl_service_connection'
